#+Title: Inference from the page fault test 
#+Date: April 18, 2017
#+Author: VLEAD Systems 


* Introduction 
  This document refers the raw data fetched from the sar test.
  

* Test Procedure and details 
  + Tool used :: sar
  + Test Subject :: Open edX on college cloud and Host Server
  + No of labs running :: 1 Lab was running and rest of them were turned off exclude server nodes.
  + Sample command 
    #+BEGIN_SRC 
    sar -B 1 10
    #+END_SRC
  + The above command transferes 10 times in 1 sec.
  + Here, -B is used to display/reporting paging statistics.

* Understanding the sample results -
  + Command used 
    #+BEGIN_SRC 
    sar -B 1 10
    #+END_SRC
  + Sample output snippet obtained . 
    #+BEGIN_SRC
     Linux 3.13.0-95-generic (vagrant-ubuntu-trusty-64) 	04/19/2017 	_x86_64_	(4 CPU)

11:26:33 AM  pgpgin/s pgpgout/s   fault/s  majflt/s  pgfree/s pgscank/s pgscand/s pgsteal/s    %vmeff
11:26:34 AM      0.00      0.00     67.00      0.00     97.00      0.00      0.00      0.00      0.00
11:26:35 AM      0.00      0.00     71.00      0.00     65.00      0.00      0.00      0.00      0.00
11:26:36 AM      0.00      0.00     23.00      0.00     55.00      0.00      0.00      0.00      0.00
11:26:37 AM      0.00      0.00     31.00      0.00     97.00      0.00      0.00      0.00      0.00
11:26:38 AM      0.00    136.00    283.00      0.00     96.00      0.00      0.00      0.00      0.00
11:26:39 AM      0.00      0.00     82.00      0.00    188.00      0.00      0.00      0.00      0.00
11:26:40 AM      0.00      0.00    124.00      0.00     96.00      0.00      0.00      0.00      0.00
11:26:41 AM      0.00      0.00     24.00      0.00     56.00      0.00      0.00      0.00      0.00
11:26:42 AM      0.00      0.00     25.00      0.00     55.00      0.00      0.00      0.00      0.00
11:26:43 AM      0.00     24.00    992.00      0.00    510.00      0.00      0.00      0.00      0.00
Average:         0.00     16.00    172.20      0.00    131.50      0.00      0.00      0.00      0.00
    #+END_SRC

  + Explaination for the above terms ::
    + pgpgin/s :: Total number of kilobytes the system paged in from
disk per second. Note: With old kernels (2.2.x) this value is a number
of blocks per second (and not kilobytes).  considered as number of
users making a request at an instance of time, where each user make a
single request.
    + pgpout/s :: Total number of kilobytes the system paged out to
disk per second. Note: With old kernels (2.2.x) this value is a number
of blocks per second (and not kilobytes).  = Time at which last
request was made - Time at which first request was made.
    + fault/s :: Number of page faults (major + minor) made by the
system per second. This is not a count of page faults that generate
I/O, because some page faults can be resolved without I/O.
    + majflt/s :: Number of major faults the system has made per
second, those which have required loading a memory page from disk.

    + pgfree/s :: Number of pages placed on the free list by the
system per second.

    + pgscank/s :: Number of pages scanned by the kswapd daemon per
second.
    + pgscand/s :: Number of pages scanned directly per second.
    + pgsteal/s :: Number of pages the system has reclaimed from cache
                   (pagecache and swapcache) per second to satisfy its
                   memory demands.
    + %vmeff :: Calculated as pgsteal / pgscan, this is a metric of
                the efficiency of page reclaim. If it is near 100%
                then almost every page coming off the tail of the
                inactive list is being reaped. If it gets too low
                (e.g. less than 30%) then the virtual memory is having
                some difficulty. This field is displayed as zero if no
                pages have been scanned during the interval of time.

  
* Raw Data 
  + [[./college-cloud/page-fault1-lab-18-04-2017.txt][collge-cloud with 1 lab]]
  
* References 
http://www.thegeekstuff.com/2011/03/sar-examples/?utm_source=feedburner

https://linux.die.net/man/1/sar
