#+Title: Inference from the page fault test on College Cloud
#+Date: April 18, 2017
#+Author: VLEAD Systems 

* Introduction 
  This document refers the raw data fetched from the sar test.

* Objective
 To count the number of page faults per second on college cloud.

* Scenario and setup
   + No Load
   + Open edX and 7 Clusters + 3 labs are running on one machine (College Cloud). 
   + OpenedX  running on one machine and 7 Clusters + 3 labs are running on another machine.
 
** Test Scenario1 
  - *Tools used:* sar (No Load).
  - *Test Subject :* OpenedX platform and college cloud running on 16GB machine.
  - *Number of labs running:* 7 clusters and 3 labs was running and were rest of them were turned off(68 lab containers)
** Test Scenario2
  - *Tools used:* sar (No Load).
  - *Test Subject :* Openedx Platform was running on 16Gb machine .
  -  *Number of labs running:* 7 clusers and 3 labs are running another machine and were rest of them were turned off (68 lab containers).


* Test Procedure and details 
** Test Procedure1
  + Tool used :: sar
  + Followed below command for testing page faults
    #+BEGIN_SRC 
    sar -B 1 10
    #+END_SRC
  + The above command transferes 10 times in 1 sec.
  + Here, -B is used to display/reporting paging statistics.
*** Understanding the below results -
  + Command used 
    #+BEGIN_SRC 
    sar -B 1 10
    #+END_SRC
  + Output snippet obtained . 
    #+BEGIN_SRC
     Linux 3.13.0-95-generic (vagrant-ubuntu-trusty-64) 	04/19/2017 	_x86_64_	(4 CPU)

11:26:33 AM  pgpgin/s pgpgout/s   fault/s  majflt/s  pgfree/s pgscank/s pgscand/s pgsteal/s    %vmeff
11:26:34 AM      0.00      0.00     67.00      0.00     97.00      0.00      0.00      0.00      0.00
11:26:35 AM      0.00      0.00     71.00      0.00     65.00      0.00      0.00      0.00      0.00
11:26:36 AM      0.00      0.00     23.00      0.00     55.00      0.00      0.00      0.00      0.00
11:26:37 AM      0.00      0.00     31.00      0.00     97.00      0.00      0.00      0.00      0.00
11:26:38 AM      0.00    136.00    283.00      0.00     96.00      0.00      0.00      0.00      0.00
11:26:39 AM      0.00      0.00     82.00      0.00    188.00      0.00      0.00      0.00      0.00
11:26:40 AM      0.00      0.00    124.00      0.00     96.00      0.00      0.00      0.00      0.00
11:26:41 AM      0.00      0.00     24.00      0.00     56.00      0.00      0.00      0.00      0.00
11:26:42 AM      0.00      0.00     25.00      0.00     55.00      0.00      0.00      0.00      0.00
11:26:43 AM      0.00     24.00    992.00      0.00    510.00      0.00      0.00      0.00      0.00
Average:         0.00     16.00    172.20      0.00    131.50      0.00      0.00      0.00      0.00
    #+END_SRC

  + Explaination for the above terms ::
    + pgpgin/s :: Total number of kilobytes the system paged in from
disk per second. Note: With old kernels (2.2.x) this value is a number
of blocks per second (and not kilobytes).  considered as number of
users making a request at an instance of time, where each user make a
single request.
    + pgpout/s :: Total number of kilobytes the system paged out to
disk per second. Note: With old kernels (2.2.x) this value is a number
of blocks per second (and not kilobytes).  = Time at which last
request was made - Time at which first request was made.
    + fault/s :: Number of page faults (major + minor) made by the
system per second. This is not a count of page faults that generate
I/O, because some page faults can be resolved without I/O.
    + majflt/s :: Number of major faults the system has made per
second, those which have required loading a memory page from disk.

    + pgfree/s :: Number of pages placed on the free list by the
system per second.

    + pgscank/s :: Number of pages scanned by the kswapd daemon per
second.
    + pgscand/s :: Number of pages scanned directly per second.
    + pgsteal/s :: Number of pages the system has reclaimed from cache
                   (pagecache and swapcache) per second to satisfy its
                   memory demands.
    + %vmeff :: Calculated as pgsteal / pgscan, this is a metric of
                the efficiency of page reclaim. If it is near 100%
                then almost every page coming off the tail of the
                inactive list is being reaped. If it gets too low
                (e.g. less than 30%) then the virtual memory is having
                some difficulty. This field is displayed as zero if no
                pages have been scanned during the interval of time.

*** Test results of OpenedX and College Cloud
**** OpenedX and 7 clusters + 3 labs are running one machine.
***** Page fault results on College Cloud
| S.No |     Lab1 |   Lab2 |   Lab3 |
|------+----------+--------+--------|
| Min  |    31.68 |  31.68 |  32.00 |
| Max  | 40875.00 | 180.81 | 536.00 |
| Avg  |  4185.56 |  49.40 |  95.79 |

***** Page fault results on OpenedX platform
| S.No | Lab1 | Lab2 | Lab3 |
|------+------+------+------|
| Min  |    23.00  |  23.00    |    23.00  |
| Max  |   992.00   | 826.00     |    1068.00  |
| Avg  |     172.20 |   151.20   |    209.49  |

*** Raw Data 
**** Raw data of 7clusters + 3labs and openedx on collge cloud.
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-one-openedx/page-fault1-lab-18-04-2017.txt][cc-with-1lab]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-one-openedx/page-fault2-lab-18-04-2017.txt][cc-with-2labs]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-one-openedx/page-fault3-lab-18-04-2017.txt][cc-with-3labs]]

**** Raw data of Openedx platform.
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-one-openedx/openedx/page-fault1-lab-18-04-2017.txt][Openedx-with-1lab]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-one-openedx/openedx/page-fault2-lab-18-04-2017.txt][OpenedX-with-2labs]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-one-openedx/openedx/page-fault3-lab-18-04-2017.txt][Openedx-with-3labs]]
  

** Test Procedure2
  + Tool used :: sar
  + Followed below command for testing page faults
    #+BEGIN_SRC 
    sar -B 1 10
    #+END_SRC
  + The above command transferes 10 times in 1 sec.
  + Here, -B is used to display/reporting paging statistics.
*** Understanding the below results -
  + Command used 
    #+BEGIN_SRC 
    sar -B 1 10
    #+END_SRC
  + Output snippet obtained . 
    #+BEGIN_SRC
Linux 3.13.0-95-generic (vagrant-ubuntu-trusty-64) 	04/21/2017 	_x86_64_	(4 CPU)

04:25:57 AM  pgpgin/s pgpgout/s   fault/s  majflt/s  pgfree/s pgscank/s pgscand/s pgsteal/s    %vmeff
04:25:58 AM      0.00      0.00     29.00      0.00    210.00      0.00      0.00      0.00      0.00
04:25:59 AM      0.00      0.00     98.00      0.00    198.00      0.00      0.00      0.00      0.00
04:26:00 AM      0.00      0.00    779.00      0.00    244.00      0.00      0.00      0.00      0.00
04:26:01 AM      0.00     68.00    184.00      0.00     58.00      0.00      0.00      0.00      0.00
04:26:02 AM      0.00      0.00  80972.28      0.00  27097.03      0.00      0.00      0.00      0.00
04:26:03 AM      0.00      0.00     34.00      0.00    101.00      0.00      0.00      0.00      0.00
04:26:04 AM      0.00    192.00     36.00      0.00     58.00      0.00      0.00      0.00      0.00
04:26:05 AM      0.00      0.00    119.00      0.00     75.00      0.00      0.00      0.00      0.00
04:26:06 AM      0.00      0.00     65.00      0.00    131.00      0.00      0.00      0.00      0.00
04:26:07 AM      0.00    116.00     65.00      0.00     59.00      0.00      0.00      0.00      0.00
Average:         0.00     37.56   8310.79      0.00   2847.35      0.00      0.00      0.00      0.00
    #+END_SRC
*** Test results of OpenedX and College Cloud
**** Opnedx platform was running one machine and 7 clusters + 3 labs are running another machine.
***** Page fault results on OpenedX.
| S.No |     Lab1 |   Lab2 |   Lab3 |
|------+----------+--------+--------|
| Min  |    29.00 |  27.00 |  27.00 |
| Max  | 80972.28 | 799.00 | 774.00 |
| Avg  |  8310.79 | 136.80 | 119.30 |

***** Page fault results on College Cloud with 7 clusters + 3 labs.
| S.No |  Lab1 |  Lab2 |  Lab3 |
|------+-------+-------+-------|
| Min  | 31.68 | 32.00 | 31.68 |
| Max  | 64.65 | 40.00 | 43.00 |
| Avg  | 37.00 | 34.83 | 34.63 |

***** Page fault results on College Cloud without 7 clusters + 71 labs.

  | S.No |     Lab1 |  Lab2 |  Lab3 |
  |------+----------+-------+-------|
  | Min  |    33.00 | 32.00 | 31.68 |
  | Max  | 21725.74 | 45.00 | 44.00 |
  | Avg  |  2350.25 | 36.47 | 36.21 |

*** Raw Data
**** Raw data of 7clusters + 3labs on college cloud
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/cc-with-7clusters%2B3labs/pagefault-1-lab.txt][cc-with-1lab]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/cc-with-7clusters%2B3labs/pagefault-2-lab.txt][cc-with-2labs]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/cc-with-7clusters%2B3labs/pagefault-3-lab.txt][cc-with-3labs]]

**** Raw data of OpenedX platform
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/openedx/pagefault-1-lab.txt][OpenedX-with-1lab]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/openedx/pagefault-2-lab.txt][OpenedX-with-2labs]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/openedx/pagefault-3-lab.txt][OpenedX-with-3labs]]

**** Raw data of without 7clusters + 71 labs on college cloud
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/cc-with-openedx/pagefault-1-lab.txt][cc-without-1lab]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/cc-with-openedx/pagefault-2-lab.txt][cc-without-2labs]]
  + [[https://github.com/openedx-vlead/college-cloud/blob/cc-april-delhi/src/pagefault/cc-with-another-openedx/cc-with-openedx/pagefault-3-lab.txt][cc-without-3labs]]

* Conlusion

* References 
http://www.thegeekstuff.com/2011/03/sar-examples/?utm_source=feedburner

https://linux.die.net/man/1/sar
