#+AUTHOR: VLEAD 
#+TITLE: Set up Syncthing Tool
#+DATE: 03-Feb-2017

* Introduction
  This document describes the step by step process for setting up the
  =syncthing= tool for synchronizing files/folders between client and server.
* What is =syncthing=?
It is a Client-Server File synchronization tool for cross platforms. A
Client will upload new files in his advertised directory, which will
automatically get synchronized to the central server.
* Install =syncthing= on client (college-cloud) machine
** Create user for =syncthing= on CentOS6.x
 Follow the below command to create a user
#+BEGIN_EXAMPLE
$ sudo adduser <username>
#+END_EXAMPLE
** Install =syncthing= on college cloud
 * On CentOS6.x platform
 * Download =syncthing= using below command.
#+BEGIN_EXAMPLE
$ wget https://github.com/syncthing/syncthing/releases/download/v0.14.23/syncthing-linux-amd64-v0.14.23.tar.gz
#+END_EXAMPLE
** Extract the download file
    Follow the below command to extract the dowload file.
#+BEGIN_EXAMPLE
$ tar xzvf syncthing-linux-amd64-v0.14.23.tar.gz
#+END_EXAMPLE
   Change directory to the extracted folder
#+BEGIN_EXAMPLE
$ cd syncthing-linux-amd64-v0.14.23
#+END_EXAMPLE
** Copy the excutable file =syncthing= to *$PATH*
  Do this with sudo privileges by typing
 #+BEGIN_EXAMPLE
 $ sudo cp syncthing /usr/local/bin/
 #+END_EXAMPLE
* Install =Syncthing= on Ubuntu16.04 machine (VLEAD-Server)
** Create user for =syncthing= on Ubuntu16.04 machine
 Follow the below command to create a user
#+BEGIN_EXAMPLE
$ sudo adduser <username>
#+END_EXAMPLE
** Install package from PPA
  Add the release PGP keys:
#+BEGIN_EXAMPLE
$ curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
#+END_EXAMPLE
  Add the "release" channel to your APT sources:
#+BEGIN_EXAMPLE
$ echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list
#+END_EXAMPLE
** Update and install =syncthing=
#+BEGIN_EXAMPLE
$ sudo apt-get update && sudo apt-get install syncthing
#+END_EXAMPLE
** Enable and start with systemd on server =(VLEAD-Server)=
#+BEGIN_EXAMPLE
$ sudo systemctl enable syncthing@$USER.service
$ sudo systemctl start syncthing@$USER.service
#+END_EXAMPLE
* Run =syncthing= programme between client and server.
 - Complete all of the above steps on your system.
 - The application is now installed, but there are a few more things we need to do before it will be ready to use.
 - Now, run the following command to run the syncthing for the first time.
#+BEGIN_EXAMPLE
$ syncthing
#+END_EXAMPLE
The syncthing process is not a daemon, which means that it runs in the
current shell session (we will get around this by implementing an
Upstart script momentarily). It will start the process and create some
necessary files.

After a moment, you will see an informational message about your Node
ID that looks like this:
#+BEGIN_EXAMPLE
[2EQK3] 15:47:15 OK: Ready to synchronize default (read-write)
[2EQK3] 15:47:15 INFO: Node 2EQK3ZR77PTBQGM44KE7VQIQG7ICXJDEOK34TO3SWOVMUL4QFBHA is "server1" at [dynamic]
#+END_EXAMPLE
When you see this, it means that the process has initialized correctly. We can now stop the process by typing
#+BEGIN_EXAMPLE
CTRL-C
#+END_EXAMPLE
This will stop the process and give us control over the terminal again.
* Configure =syncthing= programme between client and server.
  Edit the following configuration file that was created. Open the file in your text editor
#+BEGIN_EXAMPLE
$ sudo vim ~/.config/syncthing/config.xml
#+END_EXAMPLE
Look for a section that deals with the GUI. It should look like this
#+BEGIN_EXAMPLE
<gui enabled="true" tls="false">
    <address>127.0.0.1:8080</address>
</gui>
#+END_EXAMPLE
In the <address> field, change 127.0.0.1:8080 to 0.0.0.0:8080. So, your config.xml will look like below
#+BEGIN_EXAMPLE
<gui enabled="true" tls="false">
    <address>0.0.0.0:8080</address>
</gui>
#+END_EXAMPLE
Save and close the file.
* Access the WebGUI 
 - Open your browser and log into your system, Syncthing interfaces by visiting their public IP addresses and port 8080
#+BEGIN_EXAMPLE
http://clinet_public_IP:8080
http://server_public_IP:8080
#+END_EXAMPLE
* How to connect =syncthing= application between client (college-cloud) and server (VLEAD-server)?
 -  *Step1* On the *VLEAD-Server*, open the Syncthing GUI and click on the gear button and select Settings -> Show ID on the top right corner.
 -  *Step2* Copy the *VLEAD-Server ID* WebGUI, and go to the another system *(College-Cloud)* WebGUI window, click on the *Add Device* on the right side.
 -  *Step3* Paste the *system (VLEAD-Server)* in the Device section. Enter the Device name(optional). In the Addresses field, you can either enter the IP address of the other system or leave it as default.
 -  *Step4* Once you done, click on the save button. You'll be asked to restart the Syncthing. Click Restart button to activate the changes.
 -  *Step5* Now, go to the *VLEAD-Server* WebUI, you'll see a request has been sent from the *College-cloud* to connect.
* How to share files/folders between college-cloud and VLEAD-Server?
 - In order to share a folder you need to start by adding it to the Syncthing on one of the two machines. 
 - Click *Add Folder* button in the Folders section.
 - *Folder Lable* This is the name or label of the shared folder. 
 - *Folder ID* This is default ID of the folder.
 - *Folder Path* This is where you want it to store the files on the local computer. For example on client machine I might want this to be ~/Sync/MyShare share.
 - *Share With Devices* These are the computers you want to share this folder with.
 - Once you done, click on the save button.
 - Finally to share it with server. Once done you should see a new notification on server asking if you want to add the newly shared folder there as well.
 - Once done the folder should be shared and anything you put into the folder on either computer will be automatically synchronized on the other.
 
If you would like to add a more devices just follow the above steps again. 

* References
 - [[https://syncthing.net/]]
 - [[https://www.unixmen.com/syncthing-private-secure-tool-sync-filesfolders-computers/]]
 - [[http://drup.org/setting-syncthing-ubuntu-1604-server]]




